select constraints\*.xml >> IGPackage Profile.BirthDetailsEvent
select valuesets\*.xml >> IGPackage Profile.BirthDetailsEvent
select constraints\*.xml >> IGPackage Profile.AssessmentAPGAREvent
select valuesets\*.xml >> IGPackage Profile.AssessmentAPGAREvent
select constraints\*.xml >> IGPackage Profile.BreastfeedingStatusEvent
select valuesets\*.xml >> IGPackage Profile.BreastfeedingStatusEvent
select constraints\*.xml >> IGPackage Profile.NeonatalCareEvent
select valuesets\*.xml >> IGPackage Profile.NeonatalCareEvent
select constraints\*.xml >> IGPackage Profile.BirthDischargeEvent
select valuesets\*.xml >> IGPackage Profile.BirthDischargeEvent
select constraints\*.xml >> IGPackage Profile.ReferralEvent
select valuesets\*.xml >> IGPackage Profile.ReferralEvent
select constraints\*.xml >> IGPackage Profile.FollowUpEvent
select valuesets\*.xml >> IGPackage Profile.FollowUpEvent
select constraints\*.xml >> IGPackage Profile.MeasurementsEvent
select valuesets\*.xml >> IGPackage Profile.MeasurementsEvent